#!/bin/python3
import ntpath
import os
from termcolor import cprint

#os.chdir(os.path.dirname(__file__))
pwdd = os.getcwd()
#print(ntpath.basename(pwdd))
if pwdd[-1] != "/":
	pwdd = pwdd + "/"

class dir():

    def searchDir(self):
        dirChilds = []
        # fileChilds = []
        try:
            dirs = os.listdir(self.path)
        except:
            cprint("Not allowed", "red")
            return
        for d in dirs:
            if os.path.isdir(self.path + "/" + d):
                newDir = dir(self.path + "/" + d, self.depth+1, self)
               # print(newDir)
                dirChilds.append(newDir)
            else:
                cprint(("    " * (self.depth+1)) + "└─ " + d, "green")

        # return [dirChilds, fileChilds]
        return dirChilds

    def __init__(self, path, depth, parent=None):
        self.path = path
        self.depth = depth
        self.parent = parent
        cprint(self.printSelf(), "blue")
        # childs = self.searchDir()
        self.dirChilds = self.searchDir()
        # self.fileChilds = childs[1]

    def printSelf(self):
        return ("    " * self.depth) + "└─" + ntpath.basename(self.path) + "/"

root = dir(pwdd, 0)

